/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.JFrame;

/**
 *
 * @author Administrator
 */
public class VisPlanCuentas extends javax.swing.JFrame {

    /**
     * Creates new form VisPersona
     */
    public VisPlanCuentas() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        pnl_personas1 = new javax.swing.JPanel();
        btnEliminar1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_personas1 = new javax.swing.JTable();
        btnGuardar1 = new javax.swing.JButton();
        txtBuscarCedula1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_personas3 = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnModificar3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        pnl_personas2 = new javax.swing.JPanel();
        btnModificar2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_personas2 = new javax.swing.JTable();
        txtBuscarCedula2 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtBuscarCedula3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(java.awt.Color.lightGray);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("STRONGFIT");
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 25));

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        pnl_personas1.setBackground(new java.awt.Color(204, 204, 204));
        pnl_personas1.setLayout(null);

        btnEliminar1.setBackground(new java.awt.Color(102, 102, 102));
        btnEliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/eliminar.png"))); // NOI18N
        pnl_personas1.add(btnEliminar1);
        btnEliminar1.setBounds(60, 310, 50, 40);

        tbl_personas1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "DESCRIPCION DE CUENTA", "TIPO MOVIMIENTO", "TIPO DE CUENTA", "NIVEL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_personas1.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(tbl_personas1);
        tbl_personas1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tbl_personas1.getColumnModel().getColumnCount() > 0) {
            tbl_personas1.getColumnModel().getColumn(1).setResizable(false);
            tbl_personas1.getColumnModel().getColumn(1).setPreferredWidth(100);
            tbl_personas1.getColumnModel().getColumn(4).setHeaderValue("GENERO");
        }

        pnl_personas1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 355, 870, 150);

        btnGuardar1.setBackground(new java.awt.Color(102, 102, 102));
        btnGuardar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/guardar7.png"))); // NOI18N
        pnl_personas1.add(btnGuardar1);
        btnGuardar1.setBounds(10, 20, 40, 40);

        txtBuscarCedula1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarCedula1KeyTyped(evt);
            }
        });
        pnl_personas1.add(txtBuscarCedula1);
        txtBuscarCedula1.setBounds(90, 70, 150, 20);

        jLabel19.setText("Buscar cuentas:");
        pnl_personas1.add(jLabel19);
        jLabel19.setBounds(10, 70, 88, 14);

        tbl_personas3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "DESCRIPCION DE CUENTA", "TIPO MOVIMIENTO", "TIPO DE CUENTA", "NIVEL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tbl_personas3);
        tbl_personas3.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tbl_personas3.getColumnModel().getColumnCount() > 0) {
            tbl_personas3.getColumnModel().getColumn(1).setResizable(false);
            tbl_personas3.getColumnModel().getColumn(1).setPreferredWidth(100);
            tbl_personas3.getColumnModel().getColumn(4).setHeaderValue("GENERO");
        }

        pnl_personas1.add(jScrollPane4);
        jScrollPane4.setBounds(10, 100, 871, 185);

        btnAgregar.setText("ELIMINAR CUENTA");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        pnl_personas1.add(btnAgregar);
        btnAgregar.setBounds(730, 70, 150, 23);

        btnModificar3.setBackground(new java.awt.Color(102, 102, 102));
        btnModificar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/modificar.png"))); // NOI18N
        pnl_personas1.add(btnModificar3);
        btnModificar3.setBounds(10, 310, 40, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("CUENTAS HIJAS");
        pnl_personas1.add(jLabel2);
        jLabel2.setBounds(360, 310, 160, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("FORMULARIO DE INGRESO DE CUENTAS");
        pnl_personas1.add(jLabel3);
        jLabel3.setBounds(270, 20, 390, 22);

        jPanel3.add(pnl_personas1);

        jTabbedPane1.addTab("Ingresar Cuenta", jPanel3);

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        pnl_personas2.setBackground(new java.awt.Color(204, 204, 204));
        pnl_personas2.setLayout(null);

        btnModificar2.setBackground(new java.awt.Color(102, 102, 102));
        btnModificar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/modificar.png"))); // NOI18N
        pnl_personas2.add(btnModificar2);
        btnModificar2.setBounds(710, 390, 40, 40);

        tbl_personas2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CODIGO", "NOMBRE CUENTA", "MOV. CUENTA", "TIPO DE CUENTA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbl_personas2);
        tbl_personas2.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tbl_personas2.getColumnModel().getColumnCount() > 0) {
            tbl_personas2.getColumnModel().getColumn(1).setResizable(false);
            tbl_personas2.getColumnModel().getColumn(1).setPreferredWidth(100);
        }

        pnl_personas2.add(jScrollPane3);
        jScrollPane3.setBounds(10, 140, 871, 185);

        txtBuscarCedula2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarCedula2KeyTyped(evt);
            }
        });
        pnl_personas2.add(txtBuscarCedula2);
        txtBuscarCedula2.setBounds(90, 350, 660, 20);

        jLabel28.setText("Descripción:");
        pnl_personas2.add(jLabel28);
        jLabel28.setBounds(20, 350, 88, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Ingrese la descripción de la cuenta para seleccionar");
        pnl_personas2.add(jLabel5);
        jLabel5.setBounds(10, 80, 390, 22);

        jLabel20.setText("Se puede dar click en la tabla para elegir la descripción de la cuenta a modificar");
        pnl_personas2.add(jLabel20);
        jLabel20.setBounds(170, 110, 430, 20);

        txtBuscarCedula3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarCedula3KeyTyped(evt);
            }
        });
        pnl_personas2.add(txtBuscarCedula3);
        txtBuscarCedula3.setBounds(10, 110, 150, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnl_personas2.add(jComboBox1);
        jComboBox1.setBounds(760, 350, 120, 20);

        jPanel5.add(pnl_personas2);

        jTabbedPane1.addTab("Modificar Cuentas", jPanel5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 942, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarCedula1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarCedula1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarCedula1KeyTyped

    private void txtBuscarCedula2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarCedula2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarCedula2KeyTyped

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtBuscarCedula3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarCedula3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarCedula3KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisPlanCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisPlanCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisPlanCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisPlanCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisPlanCuentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    public javax.swing.JButton btnEliminar1;
    public javax.swing.JButton btnGuardar1;
    public javax.swing.JButton btnModificar2;
    public javax.swing.JButton btnModificar3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JPanel pnl_personas1;
    public javax.swing.JPanel pnl_personas2;
    public javax.swing.JTable tbl_personas1;
    public javax.swing.JTable tbl_personas2;
    public javax.swing.JTable tbl_personas3;
    public javax.swing.JTextField txtBuscarCedula1;
    public javax.swing.JTextField txtBuscarCedula2;
    public javax.swing.JTextField txtBuscarCedula3;
    // End of variables declaration//GEN-END:variables
}
